### ISSUE TITLE
Default config not defined

### ISSUE THREAD

**Issue by birgittab** [fbaiodias/react-video-recorder#10]
Hello,

I am having problems getting your video component to work with react.
I followed your instructions and it gives me this message, no matter how I try to import.

![image](https://user-images.githubusercontent.com/31894516/53881081-a397dc80-400a-11e9-931d-e60c094b2292.png)

Do you have a solution for this?

Thanks.

**Comment by fbaiodias** [comment]
Hey @birgittab!
All those props are optional, so you don't need to pass them. 
Try just using the component without passing any props like this:

```js
import VideoRecorder from 'react-video-recorder'

...
<VideoRecorder />
...
```

**Comment by birgittab** [comment]
thanks, it works!

I will be needing to save the recorded video to my computer... 
will this be a problem if I skip these props though?

**Comment by fbaiodias** [comment]
Yeah, you'll need to pass a function to `onRecordingComplete` and handle the video blob which is passed as a first argument there.

**Comment by birgittab** [comment]
ah of course! Thank you very much :)
