### ISSUE TITLE
The stop recording button is making this error:

### ISSUE THREAD

**Issue by kanon4us** [fbaiodias/react-video-recorder#127]
vendors~main.d3cc3ca2e84b8b582969.bundle.js:1 Uncaught (in promise) Error: No schema entry found for unknown
    at EBMLEncoder.writeTag (vendors~main.d3cc3ca2e84b8b582969.bundle.js:1)
    at EBMLEncoder.encodeChunk (vendors~main.d3cc3ca2e84b8b582969.bundle.js:1)
    at vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
    at Array.reduce (<anonymous>)
    at EBMLEncoder.encode (vendors~main.d3cc3ca2e84b8b582969.bundle.js:1)
    at vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
    at Array.reduce (<anonymous>)
    at encodedSizeOfEbml (vendors~main.d3cc3ca2e84b8b582969.bundle.js:1)
    at Object.makeMetadataSeekable (vendors~main.d3cc3ca2e84b8b582969.bundle.js:1)
    at main.d3cc3ca2e84b8b582969.bundle.js:1
EBMLEncoder.writeTag @ vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
EBMLEncoder.encodeChunk @ vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
(anonymous) @ vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
EBMLEncoder.encode @ vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
(anonymous) @ vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
encodedSizeOfEbml @ vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
makeMetadataSeekable @ vendors~main.d3cc3ca2e84b8b582969.bundle.js:1
(anonymous) @ main.d3cc3ca2e84b8b582969.bundle.js:1
Promise.then (async)
(anonymous) @ main.d3cc3ca2e84b8b582969.bundle.js:1

**Comment by kanon4us** [comment]
This is happening in Google Chrome Desktop at https://react-video-recorder.vercel.app/?path=/story/videorecorder--with-isflipped-false

**Comment by codyromano** [comment]
I'm experiencing the same issue.

**Comment by kanon4us** [comment]
What I can tell, the video schema object isn’t being set. In firefox, it is set to this...
![schema](https://user-images.githubusercontent.com/1626905/126908412-18b8d2e3-2b2d-4f78-9ddc-9bf36bc23b3c.jpeg)
So if there is a way to manually set it, it might resolve the issue...
However, I don't think it's possible to set it manually due to it being one part of the data stream...
![Screen Shot 2021-07-24 at 3 29 38 PM](https://user-images.githubusercontent.com/1626905/126908436-a1f7c992-99e8-4434-9271-20bce2af6ee4.jpeg)
Looking at the code just before the function that’s throwing the error, there are 72 array objects that each contain different schema types. Each of these are autogenerated as part of the video record process...
![Screen Shot 2021-07-24 at 3 34 23 PM](https://user-images.githubusercontent.com/1626905/126908454-b64dc24b-b178-4055-98f8-a5a7a47aa551.jpeg)
That shows wherein the generated metadata the issue block is.
In this next screenshot, you can see how the rest of the growing entries are “SimpleBlock”, which represent a chunk of the actual video...
I ran the video code in a Chromium browser which is a version or two behind Chrome, so it’s definitely a browser update that caused the issue.
Chromium uses the same rendering engine as Chrome, the only difference is that it has all the google tracking stripped from the browser.
I’m having no luck figuring out a workaround, so I think using another library is the only option at this time...
Here is another that I came across that supports react and works in Chrome...
Here is another that I came across that supports react and works in chrome
https://collab-project.github.io/videojs-record/#/frameworks/react

**Comment by jackguoAtJogg** [comment]
I hope this could get fixed soon since this library comes better UI than https://collab-project.github.io/videojs-record/#/frameworks/react.

**Comment by asanjeevrao** [comment]
Facing the same issue

**Comment by jmazier-j2d** [comment]
Same issue here.. Any news ? I'm also trying to figure out a workaround, I'll let you know.

**Comment by jackguoAtJogg** [comment]
I think found the issue, it seems to be an error with this `ts-ebml` library and it errors out in this function:
https://github.com/fbaiodias/react-video-recorder/blob/7c709a12c728fdf3624a07ec98d4cf29e07dc14f/src/video-recorder.js#L596

Technically if you get rid off `fixVideoMetadata` and create a new Blob from the recording, it shoud work.

**Comment by jackguoAtJogg** [comment]
I think I found the issue, is due to this library https://github.com/legokichi/ts-ebml that's not working properly.

reference issue: https://github.com/legokichi/ts-ebml/issues/33

**Comment by lukewzk** [comment]
Yup, facing the same issue here. I think it's broken for users using a combination of MacOS + chromium browsers (i.e. Google Chrome or Microsoft Edge).

**Comment by alexeymetelkinpro** [comment]
Hey there! Here is a workaround for that issue for now - https://github.com/fbaiodias/react-video-recorder/issues/130; 
Works for me! 

I also forked that fork fix to make it usable through `npm`: here is my fork - https://github.com/alexeymetelkinpro/react-video-recorder. 
To get the fix, you gotta replace the original `react-video-recorder` line with this - `"react-video-recorder": "alexeymetelkinpro/react-video-recorder"`. Or `"react-video-recorder": "alexeymetelkinpro/react-video-recorder#c4d02177de1f9f5e5f4db8bb242b195d1fed0899"` to make sure you won't get further updates from my repository, though I have no plans to ever make any changes there.

**Comment by codyromano** [comment]
@fbaiodias Thanks for your work on this! :)

**Comment by jmazier-j2d** [comment]
Still not working on my side (v3.19.1) on MacOS and Google Chrome (exact same issue). Am I the only one here ?
