### ISSUE TITLE
URGENT: React Video Recorder broken on Chrome latest + Safari latest

### ISSUE THREAD

**Issue by catoenm** [fbaiodias/react-video-recorder#130]
React Video Recorder is crashing on the latest version of chrome. I've tried versions `3.18.4`, `3.18.2`, `3.17.2`.

The following is the error message received any time the user stops recording.

![image](https://user-images.githubusercontent.com/6610700/128088000-87aecd24-2619-4a76-9509-9c6494ba32eb.png)

**Comment by DaveFerBear** [comment]
Same issue here. Current version in sandbox is broken: https://0d26g.csb.app/

**Comment by catoenm** [comment]
Seems to be an issue with the latest chrome update.

https://chromereleases.googleblog.com/

**Comment by catoenm** [comment]
This seems to be a problem with decoding schemas in EBML. 

https://github.com/legokichi/ts-ebml/issues/33#issuecomment-888800828

The following fixes the issue for me.

```
-      const elements = decoder.decode(buffer)
+      let elements = decoder.decode(buffer)
+      // see https://github.com/legokichi/ts-ebml/issues/33#issuecomment-888800828
+      const validEmlType = ['m', 'u', 'i', 'f', 's', '8', 'b', 'd']
+      elements = elements?.filter((elm) => validEmlType.includes(elm.type))
```
