### ISSUE TITLE
get-video-info.js Line 35

### ISSUE THREAD

**Issue by paulincai** [fbaiodias/react-video-recorder#14]
Hi,
just wanted to reconfirm that line 35/36 is correct cause I don't find any reference of 'remoteEventListener' but this place would be a very good place to remove the listener so I am wondering whether that is a typo:

```Javascript
 videoTag.remoteEventListener &&
        videoTag.remoteEventListener('loadeddata', handleLoadedData)

```

**Comment by fbaiodias** [comment]
Yeah, that's definitely a typo, good catch! 🙌

Do you want to fix it in a PR?

**Comment by fbaiodias** [comment]
Thanks for fixing this in #15 @paulincai!
