### ISSUE TITLE
chrome recorded vidoe can`t play in iphone safari browser

### ISSUE THREAD

**Issue by puspendra09** [fbaiodias/react-video-recorder#145]
when I record video in chrome browser using pc and stored in s3 bucket, that video play with pc browser but in iphone browser occur an error. Have an any solution to resolve this issue to play video with independ platforms.

**Comment by malavshah9** [comment]
@puspendra09  Have you found any solutions yet?

**Comment by puspendra09** [comment]
No

**Comment by puspendra09** [comment]
@malavshah9 No

**Comment by BrocoliMew** [comment]
Try to remove the mimeType in <VideoRecorder ... />
// mimeType="video/webm;codecs=vp8,opus"

**Comment by Huzaifaahmed20** [comment]
I didn't specify the mimeType, but still it doesn't work on safari browser, any solutions?

My Code:
```js
<VideoRecorder
        constraints={{ video: true, audio: true }}
        onRecordingComplete={(videoBlob) => {
            console.log('videoBlob', videoBlob);
            saveVideo(videoBlob);
        }}
 />


  const saveVideo = async (blob) => {
    try {
      if (blob) {
        const videoFormData = new FormData();
        videoFormData.append('video', blob);
        await uploadVideo.mutateAsync({ payload: videoFormData });
      }
    } catch (err) {
      Toaster.error(err);
    }
  };

```
