### ISSUE TITLE
Doesn't work with React 18

### ISSUE THREAD

**Issue by JackCompass** [fbaiodias/react-video-recorder#172]
I have been trying to integrate this package with one of my projects that is using react 18. But this package doesn't support react 18. Upgrade the package support.

**Comment by ayushidianapps** [comment]
Do we have a solution for this?

**Comment by JackCompass** [comment]
@ayushidianapps you can go with other packages. `react-media-recorder` is a good one.

**Comment by acf77** [comment]
Also, it does not work with NextJS version 12.2.4 and React 18 onwards.

**Comment by dpcdev1999** [comment]
Having this issue too

**Comment by ayushidianapps** [comment]
Thank you for your response. Quite disappointed with this but nevermind,
will switch to other package.

**Comment by NLanese** [comment]
Also having this issue, haven't found a fix anywhere. Seems like it won't be working anytime soon

**Comment by elchiconube** [comment]
Any update about it?

**Comment by GeraudWilling** [comment]
> Also, it does not work with NextJS version 12.2.4 and React 18 onwards.

What king of error are you facing?

**Comment by eman-alzouabi** [comment]
Hi @fbaiodias , I've downloaded the latest version of the package but it doesn't work, it shows only the loading screen.

**Comment by jedusei** [comment]
Hi @fbaiodias,
The peer dependencies need to be updated as well: 
https://github.com/fbaiodias/react-video-recorder/blob/9b30902f248eff7eebbe785e2eef2a409c2145d9/package.json#L49
