### ISSUE TITLE
Cannot find module 'styled-components'

### ISSUE THREAD

**Issue by kiitos-smasri** [fbaiodias/react-video-recorder#35]
after rendering component this message appears 
Cannot find module 'styled-components'

**Comment by nolanjacobson** [comment]
I am getting the same issue. Have you found a resolution?

**Comment by kiitos-smasri** [comment]
Yes i managed to solve it 
check your terminal when you try to install you will get dependency warnings 
install them all manually

**Comment by doughtyorg** [comment]
dependencies no longer auto-add so do yarn add styled-components@^4.1.1
