### ISSUE TITLE
Recording not working in Firefox

### ISSUE THREAD

**Issue by dominicphillips** [fbaiodias/react-video-recorder#41]
Looks like an issue with codecs - can I help?

**Comment by gideonibemerejr** [comment]
Having same issue -- please advice @fbaiodias

**Comment by arnklint** [comment]
I believe it's already been solved in #40 , tried a hotfix locally and that change fixed the issue. Although the fix has not made it to a release yet.

**Comment by fbaiodias** [comment]
Yeah, it looks like semantic-release didn't understand the commit message of #40 so it didn't get released. 
It's now available in [v3.17.1](https://github.com/fbaiodias/react-video-recorder/releases/tag/v3.17.1).
