### ISSUE TITLE
Guia de uso

### ISSUE THREAD

**Issue by fedeevilla** [fbaiodias/react-video-recorder#9]
Hola como estas? Te escribo para solicitar ayuda en el uso de esta libreria. Me podrías colaborar? Gracias!

**Comment by fbaiodias** [comment]
Hey, I've just added an usage section in the README with a link to the storybook which now has the list of the supported prop-types: https://github.com/fbaiodias/react-video-recorder/#usage

If you have any specific questions or problems please open another issue with them.
